
all: compile start

compile:
	rebar compile

clean:
	rebar clean

.PHONY: test start attach

test:
	rebar compile eunit

start:
	@echo -ne "[ REHC INFO ] Starting....."
	@$(RUN_ERL) -daemon $(PIPES_DIR) $(LOGS_DIR) "exec $(ERL) -config $(CONFIG_FILE) -args_file $(ARGS_FILE) -pa $(EBIN_DIR)/ -eval 'application:start(rehc).'"
	@echo "[OK]"

attach:
	@$(TO_ERL) $(PIPES_DIR) 
